name: Spring Boot® RHR
version: 0.1.1
description: Spring Boot using RHR and Maven
license: Apache-2.0
language: java
maintainers:
  - name: Erin Schnabel
    email: schnabel@us.ibm.com
    github-id: ebullient
  - name: Ozzy Osborne
    email: ozzy@ca.ibm.com
    github-id: bardweller    
default-template: default
